baseURL: http://example.org/
languageCode: en-us
title: David Byttow
theme: davidbyttow
googleAnalytics: "G-KPCBK8EW1C"
assertDir: assets
buildDrafts: false
params:
  body_classes: avenir bg-white
  background_color_class: bg-white
  custom_css:
    - css/styles.css
  twitter: https://twitter.com/davidbyttow
  youtube: https://youtube.com/davidbyttow
  medium: https://medium.com/@davidbyttow
  instagram: https://instagram.com/davidbyttow
  linkedin: https://www.linkedin.com/in/davidbyttow/
  github: https://github.com/davidbyttow

menu:
  main:
    - identifier: work
      name: Work
      url: /work
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 10
    # - identifier: videos
    #   name: Videos
    #   url: /videos
    #   weight: 100
    # - identifier: interests
    #   name: Interests
    #   url: /interests
    # - identifier: blog
    #   name: Writing
    #   url: /blog
